using FluentAssertions;
using LicensePlatform.Security.LicenseGeneration;
using Xunit;

namespace LicensePlatform.Tests.UnitTests.LicenseGeneration
{
    /// <summary>
    /// Tests for the LicenseKeyGenerator covering key generation, format validation,
    /// and product code embedding in keys.
    /// </summary>
    public class LicenseKeyGeneratorTests
    {
        private readonly LicenseKeyGenerator _generator;

        public LicenseKeyGeneratorTests()
        {
            _generator = new LicenseKeyGenerator();
        }

        [Fact]
        public void GenerateKey_ValidProductCode_ReturnsCorrectFormat()
        {
            // Arrange
            var productCode = "CLEANER";

            // Act
            var key = _generator.GenerateKey(productCode);

            // Assert
            key.Should().NotBeNullOrWhiteSpace("key must be generated");
            _generator.IsValidFormat(key).Should().BeTrue("generated key must pass format validation");
            key.Should().StartWith($"{productCode.ToUpper()}-",
                "key must start with the uppercase product code followed by a dash");
        }

        [Fact]
        public void GenerateKey_DifferentCalls_ProduceDifferentKeys()
        {
            // Arrange
            var productCode = "OPTIMIZER";

            // Act
            var key1 = _generator.GenerateKey(productCode);
            var key2 = _generator.GenerateKey(productCode);
            var key3 = _generator.GenerateKey(productCode);

            // Assert
            key1.Should().NotBe(key2, "first two keys should differ");
            key1.Should().NotBe(key3, "first and third keys should differ");
            key2.Should().NotBe(key3, "second and third keys should differ");
        }

        [Fact]
        public void IsValidFormat_ValidKey_ReturnsTrue()
        {
            // Arrange
            var key = _generator.GenerateKey("TEST");

            // Act
            var result = _generator.IsValidFormat(key);

            // Assert
            result.Should().BeTrue("a key generated by the system must be valid");
        }

        [Fact]
        public void IsValidFormat_InvalidKey_ReturnsFalse()
        {
            // Arrange
            var invalidKey = "NOT-A-VALID-KEY-FORMAT-AT-ALL";

            // Act
            var result = _generator.IsValidFormat(invalidKey);

            // Assert
            result.Should().BeFalse("an incorrectly formatted key must fail validation");
        }

        [Fact]
        public void IsValidFormat_NullKey_ReturnsFalse()
        {
            // Act
            var result = _generator.IsValidFormat(null!);

            // Assert
            result.Should().BeFalse("null key must return false");
        }

        [Fact]
        public void IsValidFormat_EmptyKey_ReturnsFalse()
        {
            // Act
            var result = _generator.IsValidFormat(string.Empty);

            // Assert
            result.Should().BeFalse("empty key must return false");
        }

        [Fact]
        public void GenerateKey_ProductCodeInKey_ReturnsTrue()
        {
            // Arrange
            var productCode = "BACKUP";

            // Act
            var key = _generator.GenerateKey(productCode);

            // Assert
            key.Should().Contain(productCode.ToUpper(),
                "the generated key must contain the product code prefix");
        }

        [Fact]
        public void GenerateKey_ShortProductCode_ProducesValidKey()
        {
            // Arrange — 2-character code is the minimum per the regex
            var productCode = "AB";

            // Act
            var key = _generator.GenerateKey(productCode);

            // Assert
            _generator.IsValidFormat(key).Should().BeTrue("short product codes should produce valid keys");
            key.Should().StartWith("AB-");
        }

        [Fact]
        public void GenerateKey_MaxProductCode_ProducesValidKey()
        {
            // Arrange — up to 50 characters
            var productCode = new string('X', 50);

            // Act
            var key = _generator.GenerateKey(productCode);

            // Assert
            _generator.IsValidFormat(key).Should().BeTrue("50-char product codes should produce valid keys");
        }

        [Fact]
        public void GenerateKey_EmptyProductCode_ThrowsException()
        {
            // Act & Assert
            Action act = () => _generator.GenerateKey(string.Empty);
            act.Should().Throw<ArgumentException>("empty product code must throw");
        }

        [Fact]
        public void GenerateKey_LowercaseProductCode_NormalizesToUppercase()
        {
            // Arrange
            var productCode = "cleaner";

            // Act
            var key = _generator.GenerateKey(productCode);

            // Assert
            key.Should().StartWith("CLEANER-", "product code should be uppercased in the key");
        }
    }
}
